config/routes.rb
Crowdboarding::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users, :only => [:show, :index, :update]
  
  resources :events do
    get :autocomplete_city_name, :on => :collection
    resources :comments, :only => [:index, :create]
  end
  
  resources :friendships, :only => [:create, :destroy, :index]
  resources :attendances, :only => [:create, :destroy]
  resources :tags, :only => [:index, :show]
  resources :authentications, :only => [:index, :create, :destroy]
    
  match 'contact' => 'home#contact', :as => :contact
  match 'about' => 'home#about', :as => :about
  match 'help' => 'home#help', :as => :help
  match 'welcome' => 'home#welcome', :as => :welcome
  
  match '/auth/:provider/callback' => 'authentications#create'
  
  match 'change_local/:local' => 'application#change_local', :as => :change_local
  
  root :to => "home#index"

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.from_now.recent.page(params[:page]).per(10)
    @events_from_now = Event.from_now.limit(5)
    @active_users = User.limit(10)
    @tags = Event.tag_counts_on(:tags)
  end
end

app/views/home/_footer.html.haml
#wrapper_helmet
	#helmet
#wrapper_footer
	#footer
		.section
			.footer_title
				=t('footer.languages')
			.footer_options
				%ul
					%li=link_to "Español", change_local_path("es")
					%li=link_to "English", change_local_path("en")
		.section
			.footer_title
				=t('footer.web')
			.footer_options
				%ul
					%li= link_to t('footer.about'), about_path
					%li= link_to t('footer.contact'), contact_path
					%li= link_to t('footer.help'), help_path
					%li= link_to t('footer.riders'), users_path
					%li= link_to t('footer.authentications'), authentications_path
		.section
			.footer_title
				=t('footer.follow_us')
			.footer_options
				%ul
					%li=link_to "Blog", t('footer.blog_link')
					%li=link_to "Twitter", t('footer.twitter_link')
					%li=link_to "Facebook", t('footer.facebook_link')	

app/views/home/_info.html.haml
.info_block.info_block_alpha
	.info_block_content
		%h2.green_bottom
			=t('info.header_1')
		%p
			=t('info.text_1')
.info_block
	.info_block_content
		%h2.black_bottom
			=t('info.header_2')
		%p
			=t('info.text_2')
.info_block.info_block_omega
	.info_block_content
		%h2.red_bottom
			=t('info.header_3')
		%p
			=t('info.text_3')

app/views/home/_noticebar.html.haml
- if flash[:notice] or flash[:error]
	#wrapper_noticebar
		#noticebar
			#message{:class => flash[:notice] ? "success" : "failure"}
				=flash[:notice] || flash[:error]

app/views/home/_sidebar.html.haml
#sidebar
	.sidebar_content
		.block.first_block
			%h4 It's happening!
			%ul
				- @events_from_now.each do |event|
					%li=link_to "#{event.name} at #{Time.now.strftime('%H:%M')}", event_path(event)
			.see_all
				=link_to "see more", "#"
		.block
			%h4 Hot items
			%p
				- tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
					= link_to tag.name, tag_path(tag.id), :class => css_class
			.see_all
				=link_to "see more", "#"
		.block		
			%h4 Active riders in Madrid
			.avatars.indent
				- @active_users.each do |user|
					=link_to raw("#{image_tag user.avatar(:small), :width => 25, :height => 25, :title => user.nickname}"), user_path(user)
			.see_all
				=link_to "see more", "#"
		
		.block
			%h4 Recent events
			%p.indent Lorem ipsum dolor sit amet, consectetur adipisicing elit
			
		.block.last_block		
			%h4 Most used spots
			%p.indent Lorem ipsum dolor sit amet, consectetur adipisicing elit

app/views/home/_splash.html.haml
.splash_text
	#title
		= sanitize(t('header.title'))
	#subtitle
		= t('header.subtitle')
	=link_to "#{t('header.join')} »", new_user_registration_path

app/views/home/about.html.haml
%h2 About us
- 2.times do 
	%p Lorem ipsum dolor sit amet
%h2 About Crowdboarding
%p Crowdboarding is a very nice page blablablablalba. We came up with the idea because blablablablab. Hey! did you knew that blalbalbalba
%p Crowdboarding is open source! Check it out at #{ link_to "Github", "https://github.com/michaelkoper/crowdboarding" }
%p We use this #{ link_to "color pallet", "http://www.colourlovers.com/palette/1559370/Crowdboarding"}
%p We use this awesome #{ link_to "icon set ", "http://somerandomdude.com/projects/iconic/" }
%p And ofcourse credits for the following opensource technologies we used:
%ul
	%li #{ link_to "Ruby on Rails 3.0.7", "http://rubyonrails.org/" }
	%li	#{ link_to "Compass", "http://960.gs/" } (CSS Authoring Framework)
	%li #{ link_to "960 Grid system", "http://compass-style.org/" } 
	%li	#{ link_to "Sass", "http://sass-lang.com/" } (Syntactically Awesome Stylesheets)
	%li	#{ link_to "Haml", "http://haml-lang.com/" }
	%li #{ link_to "jQuery", "http://jquery.com/" } (javascript framework)
	%li	#{ link_to "Postgresql", "http://www.postgresql.org/" } 
	%li #{ link_to "CSS3", "http://www.w3schools.com/css3/" } (because we hate Internet Explorer 6,7 &amp; 8)
	%li #{ link_to "Html5", "http://www.w3schools.com/html5/default.asp" } 
	%li #{ link_to "RSpec", "https://github.com/dchelimsky/rspec" } (Behaviour Driven Development framework for Ruby)
	%li #{ link_to "Capybara", "https://github.com/jnicklas/capybara" } (Acceptance test framework for web applications)
	%li #{ link_to "Formtastic", "https://github.com/justinfrench/formtastic" } (A Rails form builder plugin with semantically rich and accessible markup.)
	%li #{ link_to "Typus", "https://github.com/fesplugas/typus" } (Ruby on Rails Admin Panel (Engine))
	%li #{ link_to "Kaminari", "https://github.com/amatsuda/kaminari" } (A Scope &amp; Engine based, clean, powerful, customizable and sophisticated paginator for Rails 3)
	%li #{ link_to "Devise", "https://github.com/plataformatec/devise" } (Flexible authentication solution for Ruby on Rails)
	%li #{ link_to "CanCan", "https://github.com/ryanb/cancan" } (Authorization Gem for Ruby on Rails)

app/views/home/contact.html.haml
%h2 Contact page
- 2.times do 
	%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/home/help.html.haml
%h2 Help
- 2.times do 
	%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/home/index.html.haml
%h2= "Events in Madrid, Spain"
= paginate @events
.events
	=render @events
= paginate @events
- content_for :sidebar_right do
	=render :partial => "home/sidebar"
-# #splash
	=# image_tag "splash2.png"
-# #home_section
-# 	.column
-# 		%h2 It's fun
-# 		%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
-# 	.column
-# 		%h2 It's free
-# 		%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.	
-# 	.column
-# 		%h2 It's awesome
-# 		%p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

app/views/home/welcome.html.haml
%h2.huge=t("welcome.title")
%p.big=t("welcome.subtitle")

%h3=t("welcome.first_steps")
.welcome_steps
	.step.alpha
		.step_container
			=image_tag("welcome_1.png")
			%h4=t("welcome.step_1.title")
			%p=t("welcome.step_1.text")
	.step
		.step_container
			=image_tag("welcome_2.png")
			%h4=t("welcome.step_2.title")
			%p=t("welcome.step_2.text")
	.step.omega
		.step_container
			=image_tag("welcome_3.png")
			%h4=t("welcome.step_3.title")
			%p=t("welcome.step_3.text")